### ISSUE TITLE
Auto Retrive cookies.

### ISSUE THREAD

**Issue by jollyolliel** [HanaokaYuzu/Gemini-API#14]
In the docs it shows that we can use browser-cookies3 to automaticaly retrive cookies. Could you add in the docs a small discription on how to use it?

**Comment by HanaokaYuzu** [comment]
Try the following snippet with necessary asyncio boilerplate:

sh:

```sh
pip install -U gemini_webapi
pip install -U browser-cookies3
```

Python:

```python
client = GeminiClient()
await client.init()
```
