### ISSUE TITLE
How to select version?

### ISSUE THREAD

**Issue by npow** [HanaokaYuzu/Gemini-API#15]
Hi, Gemini has versions `1.0` and `1.5`. Is there a way to specify the version when initializing `GeminiClient`? What is the default version used?

**Comment by jollyolliel** [comment]
Refer to #5. The 1.5 is the Advacted (Refering to #5 )

**Comment by npow** [comment]
So by default it should be using `1.0`? Reason I'm asking is because the limits are different (15 RPM vs 2 RPM for 1.5) but it seems like I'm being throttled way too early if I'm on 1.0

**Comment by npow** [comment]
I took a quick look, and I do see the model version in the payload. You seem to be using a different [endpoint](https://github.com/HanaokaYuzu/Gemini-API/blob/02a92d3a4ac388c75afb2970e61b6a5eeca211c1/src/gemini_webapi/constants.py#L6) for GenerateContent though. I'm seeing `https://alkalimakersuite-pa.clients6.google.com/$rpc/google.internal.alkali.applications.makersuite.v1.MakerSuiteService/GenerateContent
` from `aistudio.google.com`

```
["models/gemini-1.0-pro",[[[[null,"hi"]],"user"]
```

vs

```
["models/gemini-1.5-pro-latest",[[[[null,"hi"]]
```

**Comment by jollyolliel** [comment]
I didn't make this so I don't know but you could try mess around with the code and see if there is a difference. Also aistudio.google.com is basically just a "more advanced" way to chat with the Gemini 1.0 and 1.5 models

**Comment by HanaokaYuzu** [comment]
As @jollyolliel mentioned, this library is backed on [Gemini web app](https://gemini.google.com/app) instead of [Google AI Studio](https://aistudio.google.com/app). 

As far as I know, there is no option in the web app to let user choose model version (unless you subscribed to Gemini Advanced, which allows you to use 1.0 Ultra model). Since google hasn't announced model version change for Gemini web app, I believe it's still using 1.0 pro, with extra ability to fetch real time information from internet, and has no limit on request frequency.

**Comment by chrisdlees** [comment]
@HanaokaYuzu Sorry to bug you, but will being subscribed to Gemini Advanced and using that account's cookie allow you to use the Ultra model with the unofficial API? 

Google is giving away 2 months of free trial to Gemini Advanced, if you sign up for a 2-month, 1TB, Google One trial. I've been able to sign up with both my primary Google account and a throwaway account created just prior to signing up for the trial. This is with United States accounts, btw.

**Comment by HanaokaYuzu** [comment]
@chrisdlees Sorry but I haven't been able to test this package with advanced subscription (for personal reason I'm not going to activate the free trial). Likely this package will not work as expected, but still, I'm not sure.
