### ISSUE TITLE
[feature request] webapi change :D

### ISSUE THREAD

**Issue by 0wwafa** [HanaokaYuzu/Gemini-API#19]
I think that the webapi at https://aistudio.google.com/app/prompts/new_chat is way better.
for text generation it's the best, expecially if you use the flash model and not the "pro".

Or perhaps I have not understood the purpose of this repository.. in that case I apologize.

**Comment by HanaokaYuzu** [comment]
As you may realized, Gemini web app and Gemini in Google AI studio are two independent projects, and this repository is built on the former one. 

For the one you used in AI studio, Google has an official api and python SDK which you can found [here](https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=python).

**Comment by 0wwafa** [comment]
> As you may realized, Gemini web app and Gemini in Google AI studio are two independent projects, and this repository is built on the former one.
> 
> For the one you used in AI studio, Google has an official api and python SDK which you can found [here](https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=python).

I know that. So what is exactly the purpose of this project?

**Comment by HanaokaYuzu** [comment]
This is just a python wrapper. It allows you to interact with the web app in any python environment instead of in browser only.

**Comment by 0wwafa** [comment]
> This is just a python wrapper. It allows you to interact with the web app in any python environment instead of in browser only.



> This is just a python wrapper. It allows you to interact with the web app in any python environment instead of in browser only.



> This is just a python wrapper. It allows you to interact with the web app in any python environment instead of in browser only.

I understand.. and what the advantage compared of using the official api and python SDK?

**Comment by HanaokaYuzu** [comment]
No you don't. The official SDK is for the model in AI studio, while this repo is for the web app. They are for different purposes.

**Comment by 0wwafa** [comment]
> No you don't. The official SDK is for the model in AI studio, while this repo is for the web app. They are for different purposes.

can you explain me the "different purposes" ? I still don't get it.

**Comment by realgorlix** [comment]
Hello I have the same question what are the benefits of using this project? I came from DuckDuckGo Reverse API projects and here it's a different story where google gives you free API keys and access. How is it beneficial for people to use the web reverse api wrapper instead of official token?

**Comment by HanaokaYuzu** [comment]
> Hello I have the same question what are the benefits of using this project? I came from DuckDuckGo Reverse API projects and here it's a different story where google gives you free API keys and access. How is it beneficial for people to use the web reverse api wrapper instead of official token?

Pros:
- Built-in internet access and image generation ability
- Unlimited usage, completely free
- Access to Gemini Extensions (Google workspace, Youtube, etc)
- Certain web exclusive models and Gemini Advanced exclusive features
- Access to thoughts with thinking models (right now thoughts are not accessible with `google-genai` python sdk, only available in AI studio)
- Optionally keep all conversation history with your account

Cons:
- Not as stable
- No system prompt
- No safety settings
- Limited models choices
- Less control over the whole process
