### ISSUE TITLE
similar thing for gpt ?

### ISSUE THREAD

**Issue by foremtehan** [HanaokaYuzu/Gemini-API#27]
The current library is great for gemini, and thank you for that. do you know of any similar libraries for chatgpt that leverage web cookies for integrating with the api?

**Comment by HanaokaYuzu** [comment]
While I'm not using one of them yet, there should be pretty much such libraries on Github. Try searching for [gpt api](https://github.com/search?q=gpt+api&type=repositories) or [gpt reverse](https://github.com/search?q=gpt+reverse&type=repositories)
