### ISSUE TITLE
socks proxies

### ISSUE THREAD

**Issue by bejokun** [HanaokaYuzu/Gemini-API#42]
is proxies also support for socks ?

**Comment by bejokun** [comment]
also if possible to disable error from httpx
httpx.ConnectError
httpx.Timeout
httpx etc

**Comment by HanaokaYuzu** [comment]
> is proxies also support for socks ?

While socks support doesn't come with this package, you can manually install additional dependencies to have it enabled. See https://www.python-httpx.org/advanced/proxies/#socks

**Comment by HanaokaYuzu** [comment]
> also if possible to disable error from httpx httpx.ConnectError httpx.Timeout httpx etc

No plan for that. Usually these are client side specific errors caused by your internet environment. You may need to fix connectivity problems before using the API.
