### ISSUE TITLE
_Secure1PSIDTS

### ISSUE THREAD

**Issue by Ryy00** [HanaokaYuzu/Gemini-API#47]
Hi can you help me bro? About 1PSIDTS well i follow ur instructions about it i created many accs with 1PSIDTS i never been use it when i get 1PSIDTS cookie i logout my gmail acc and switch other one but its says on my api 1psidts could get expired frequently please update ur cookies is this a bug?? i will donate if u fix the api please bro i really need this

**Comment by HanaokaYuzu** [comment]
> i logout my gmail acc

That's exactly the reason. Basically logging out means getting your current cookies expired right now. In the current version you don't need to do anything after copying cookies (or you can close your browser after that) and the cookies will automatically get refreshed in background. Just remember DO NOT log out your google account.

**Comment by HanaokaYuzu** [comment]
Sorry there was a depreciated argument which caused this error, which should be fixed in the latest update.
