### ISSUE TITLE
Circular Import error

### ISSUE THREAD

**Issue by SatoX69** [HanaokaYuzu/Gemini-API#8]
Self explanatory title, I keep getting some circular import error when I try using your example snippet given in the readme.js (the first snippet)

**Comment by HanaokaYuzu** [comment]
Guess you named your python script with 'gemini.py', which is the same name as package name. 

In next version the import path will be updated to avoid such confusion in the future.

**Comment by SatoX69** [comment]
> Guess you named your python script with 'gemini.py', which is the same name as package name.
> 
> In next version the import path will be updated to avoid such confusion in the future.

Damnnnnn, Actually yeah I did name it gemini.py

**Comment by HanaokaYuzu** [comment]
In the latest version (v0.5.0) package import name has been changed to `gemini_webapi`.
